-- Create services table
CREATE TABLE IF NOT EXISTS services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    icon TEXT, -- Stores Lucide icon name, e.g., 'Palette', 'Code'
    features TEXT[], -- Array of feature strings
    color TEXT, -- Tailwind gradient classes
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE services ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Public services are viewable by everyone" ON services
    FOR SELECT USING (true);

CREATE POLICY "Services are editable by authenticated users only" ON services
    FOR ALL USING (auth.role() = 'authenticated');

-- Insert initial data (optional, based on current hardcoded data)
INSERT INTO services (title, slug, description, icon, features, color) VALUES
('Design Gráfico', 'design-grafico', 'Criação de identidades visuais, logotipos, materiais impressos e digitais que transmitem a essência da sua marca.', 'Palette', ARRAY['Logotipos e Identidade Visual', 'Material Gráfico', 'Banners e Flyers', 'Cartões de Visita'], 'from-pink-500 to-rose-600'),
('Fotografia', 'fotografia', 'Sessões fotográficas profissionais para produtos, eventos, retratos e arquitetura com qualidade excepcional.', 'Camera', ARRAY['Fotografia de Produtos', 'Eventos Corporativos', 'Retratos Profissionais', 'Fotografia Arquitetônica'], 'from-blue-500 to-cyan-600'),
('Desenvolvimento de Sites', 'desenvolvimento-web', 'Websites modernos, responsivos e otimizados para SEO, desenvolvidos com as mais recentes tecnologias.', 'Code', ARRAY['Sites Responsivos', 'E-commerce', 'Landing Pages', 'Sistemas Web'], 'from-green-500 to-emerald-600'),
('Dashboards Power BI', 'dashboards-power-bi', 'Visualização inteligente de dados com dashboards interativos que transformam informações em insights.', 'BarChart3', ARRAY['Dashboards Interativos', 'Relatórios Automatizados', 'Análise de Dados', 'KPIs Personalizados'], 'from-yellow-500 to-orange-600'),
('Produção com IA', 'videos-com-ia', 'Criação de conteúdo audiovisual inovador utilizando inteligência artificial para resultados únicos.', 'Video', ARRAY['Vídeos Promocionais', 'Animações com IA', 'Edição Avançada', 'Motion Graphics'], 'from-purple-500 to-violet-600'),
('Tráfego Pago', 'trafego-pago', 'Campanhas otimizadas no Google Ads e Meta Ads para maximizar seu ROI e alcançar seu público-alvo.', 'Target', ARRAY['Google Ads', 'Meta Ads (Facebook/Instagram)', 'Otimização de Campanhas', 'Relatórios Detalhados'], 'from-red-500 to-pink-600'),
('Manutenção de Computadores', 'manutencao-de-computadores', 'Suporte técnico especializado para manter seus equipamentos funcionando com máxima performance.', 'Wrench', ARRAY['Diagnóstico Completo', 'Limpeza e Otimização', 'Instalação de Software', 'Suporte Remoto'], 'from-gray-500 to-slate-600'),
('Instalação de Câmeras CFTV', 'instalacao-cftv', 'Sistemas de segurança avançados com câmeras de alta definição e monitoramento remoto.', 'Shield', ARRAY['Câmeras HD/4K', 'Monitoramento Remoto', 'Gravação em Nuvem', 'Instalação Profissional'], 'from-indigo-500 to-blue-600');
